/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FilterContentDialog.java
 *
 * Created on 4-Feb-2012, 7:05:35 PM
 */
package ca.ubc.magic.profiler.partitioning.view.filter;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author nima
 */
public class FilterContentDialog extends javax.swing.JDialog {
    
    List<FilterUpdateListener> mListenerList;

    /** Creates new form FilterContentDialog */
    public FilterContentDialog(java.awt.Frame parent, boolean modal,
            String filterName, String filterContent) {
        super(parent, modal);
        initComponents();
        filterNameLabel.setText(filterName);
        filterContentBox.setText(filterContent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterContentLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filterContentBox = new javax.swing.JTextArea();
        filterOkButton = new javax.swing.JButton();
        filterNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ca.ubc.magic.profiler.simulator.view.DistSimulatorApp.class).getContext().getResourceMap(FilterContentDialog.class);
        filterContentLabel.setFont(resourceMap.getFont("filterContentLabel.font")); // NOI18N
        filterContentLabel.setText(resourceMap.getString("filterContentLabel.text")); // NOI18N
        filterContentLabel.setName("filterContentLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        filterContentBox.setColumns(20);
        filterContentBox.setLineWrap(true);
        filterContentBox.setRows(5);
        filterContentBox.setWrapStyleWord(true);
        filterContentBox.setName("filterContentBox"); // NOI18N
        jScrollPane1.setViewportView(filterContentBox);

        filterOkButton.setText(resourceMap.getString("filterOkButton.text")); // NOI18N
        filterOkButton.setName("filterOkButton"); // NOI18N
        filterOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterOkButtonActionPerformed(evt);
            }
        });

        filterNameLabel.setText(resourceMap.getString("filterNameLabel.text")); // NOI18N
        filterNameLabel.setName("filterNameLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filterContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterOkButton)
                    .addComponent(filterNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterOkButtonActionPerformed
        if (mListenerList == null)
            return;
        for (FilterUpdateListener l : mListenerList)
            l.updateFilter(filterNameLabel.getText(), filterContentBox.getText());
        this.setVisible(Boolean.FALSE);
    }//GEN-LAST:event_filterOkButtonActionPerformed

   public void addFilterUpdateListener(FilterUpdateListener l){
       if (mListenerList == null)
           mListenerList = new ArrayList<FilterUpdateListener>();
       mListenerList.add(l);
   }
   
   public void removeFilterUpdateListener(FilterUpdateListener l){
       if (mListenerList != null && mListenerList.contains(l))
           mListenerList.remove(l);
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea filterContentBox;
    private javax.swing.JLabel filterContentLabel;
    private javax.swing.JLabel filterNameLabel;
    private javax.swing.JButton filterOkButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
