/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimulationUnitCustomization.java
 *
 * Created on 1-May-2012, 4:11:16 PM
 */
package ca.ubc.magic.profiler.partitioning.view;

import ca.ubc.magic.profiler.dist.control.Constants;
import ca.ubc.magic.profiler.dist.model.Module;
import ca.ubc.magic.profiler.dist.model.ModuleModel;
import ca.ubc.magic.profiler.simulator.framework.SimulationFramework;
import ca.ubc.magic.profiler.simulator.framework.SimulationFrameworkHelper;
import ca.ubc.magic.profiler.simulator.framework.SimulationUnit;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nima
 */
public class SimulationUnitCustomization extends javax.swing.JDialog {

    private SimulationUnit mTemplate;
    private SimulationFramework mSimFramework;
    
    /** Creates new form SimulationUnitCustomization */
    public SimulationUnitCustomization(java.awt.Frame parent, boolean modal,
            SimulationFramework simFramework, SimulationUnit template) {
        super(parent, modal);
        initComponents();
        
        mSimFramework = simFramework;
        mTemplate = new SimulationUnit(template);
        generateModuleRows();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customizeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        moduleNameTable = new javax.swing.JTable();
        addUnitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ca.ubc.magic.profiler.simulator.view.DistSimulatorApp.class).getContext().getResourceMap(SimulationUnitCustomization.class);
        customizeLabel.setText(resourceMap.getString("customizeLabel.text")); // NOI18N
        customizeLabel.setName("customizeLabel"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        moduleNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Module Name", "Module Partition"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        moduleNameTable.setName("moduleNameTable"); // NOI18N
        jScrollPane1.setViewportView(moduleNameTable);
        moduleNameTable.getColumnModel().getColumn(0).setMinWidth(50);
        moduleNameTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        moduleNameTable.getColumnModel().getColumn(0).setMaxWidth(50);
        moduleNameTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("moduleNameTable.columnModel.title2")); // NOI18N
        moduleNameTable.getColumnModel().getColumn(1).setResizable(false);
        moduleNameTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("moduleNameTable.columnModel.title0")); // NOI18N
        moduleNameTable.getColumnModel().getColumn(2).setMinWidth(150);
        moduleNameTable.getColumnModel().getColumn(2).setPreferredWidth(150);
        moduleNameTable.getColumnModel().getColumn(2).setMaxWidth(150);
        moduleNameTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("moduleNameTable.columnModel.title1")); // NOI18N

        addUnitButton.setText(resourceMap.getString("addUnitButton.text")); // NOI18N
        addUnitButton.setName("addUnitButton"); // NOI18N
        addUnitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUnitButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addUnitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUnitButton)
                    .addComponent(cancelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUnitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUnitButtonActionPerformed
        StringBuilder builder = new StringBuilder();
        for (int i =0; i < ((DefaultTableModel)moduleNameTable.getModel()).getRowCount(); i++){
            Integer partitionId = ((Integer)((DefaultTableModel)moduleNameTable.getModel()).getValueAt(i, 2));
            if (partitionId == -1)
                builder.append(Constants.DONT_CARE_CHAR);
            else
                builder.append(Integer.toString(partitionId));
        }
        SimulationUnit unit = SimulationFrameworkHelper.getUnitFromSig(builder.toString(), mTemplate, Boolean.FALSE);
        mSimFramework.addUnit(unit, Boolean.FALSE);
        this.setVisible(Boolean.FALSE);
    }//GEN-LAST:event_addUnitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(Boolean.FALSE);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void generateModuleRows(){
        int id = 0;
        for (Module m : mTemplate.getDistModel().getModuleMap().values())
            ((DefaultTableModel)moduleNameTable.getModel()).addRow(new Object[]{id++, 
                m.getName(), m.getPartitionId()});
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUnitButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel customizeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable moduleNameTable;
    // End of variables declaration//GEN-END:variables
}
