/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ubc.magic.profiler.simulator.view;

import ca.ubc.magic.profiler.dist.model.Host;
import ca.ubc.magic.profiler.dist.model.report.ReportModel;
import ca.ubc.magic.profiler.simulator.control.ISimulatorListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nima
 */
public class DistSimulatorRunBox extends javax.swing.JDialog implements ISimulatorListener {

    public void unitSimulationOver(ReportModel model) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void valueChanged(ReportModel report) {
        fromLabelText.setText(report.getUnitModel().getFrom());
        toLabelText.setText(report.getUnitModel().getTo());
        executionLabelText.setText(Double.toString(report.getCostModel().getExecutionCost()));
        communicationLabelText.setText(Double.toString(report.getCostModel().getCommunicationCost()));
        totalLabelText.setText(Double.toString(report.getCostModel().getTotalCost()));
        if (!mHostAdded) {
            for (Host host : report.getHostModel())
               ((DefaultTableModel)hostTable.getModel()).addRow(
                       new Object[]{host.toString()});
            mHostAdded = true;  
        }
        if (report.isFinalized()){
            doneLabel.setText("DONE!");
        }
    }    
       
    /** Creates new customizer DistSimulatorRunBox */
    public DistSimulatorRunBox(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }               

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exchangePanel = new javax.swing.JPanel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        fromLabelText = new javax.swing.JLabel();
        toLabelText = new javax.swing.JLabel();
        costPanel = new javax.swing.JPanel();
        executionLabel = new javax.swing.JLabel();
        executionLabelText = new javax.swing.JLabel();
        communicatoinLabel = new javax.swing.JLabel();
        communicationLabelText = new javax.swing.JLabel();
        totalLabelText = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        reportTitleLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        hostTable = new javax.swing.JTable();
        doneLabel = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exchangePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Unit Exchange Information"));
        exchangePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fromLabel.setFont(new java.awt.Font("Ubuntu", 1, 15));
        fromLabel.setText("From  Module: ");

        toLabel.setFont(new java.awt.Font("Ubuntu", 1, 15));
        toLabel.setText("To       Module: ");

        org.jdesktop.layout.GroupLayout exchangePanelLayout = new org.jdesktop.layout.GroupLayout(exchangePanel);
        exchangePanel.setLayout(exchangePanelLayout);
        exchangePanelLayout.setHorizontalGroup(
            exchangePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(exchangePanelLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(exchangePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(exchangePanelLayout.createSequentialGroup()
                        .add(fromLabel)
                        .add(42, 42, 42)
                        .add(fromLabelText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                    .add(exchangePanelLayout.createSequentialGroup()
                        .add(toLabel)
                        .add(41, 41, 41)
                        .add(toLabelText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)))
                .addContainerGap())
        );
        exchangePanelLayout.setVerticalGroup(
            exchangePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(exchangePanelLayout.createSequentialGroup()
                .add(exchangePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(fromLabel)
                    .add(fromLabelText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(exchangePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(toLabelText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(toLabel))
                .addContainerGap())
        );

        getContentPane().add(exchangePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 630, 81));

        costPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cost Information"));
        costPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        executionLabel.setFont(new java.awt.Font("Ubuntu", 1, 15));
        executionLabel.setText("Execution Cost:");

        communicatoinLabel.setFont(new java.awt.Font("Ubuntu", 1, 15));
        communicatoinLabel.setText("Communicaton Cost:");

        totalLabel.setFont(new java.awt.Font("Ubuntu", 1, 15));
        totalLabel.setText("Total Cost:");

        org.jdesktop.layout.GroupLayout costPanelLayout = new org.jdesktop.layout.GroupLayout(costPanel);
        costPanel.setLayout(costPanelLayout);
        costPanelLayout.setHorizontalGroup(
            costPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(costPanelLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(costPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(costPanelLayout.createSequentialGroup()
                        .add(executionLabel)
                        .add(40, 40, 40)
                        .add(executionLabelText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                    .add(costPanelLayout.createSequentialGroup()
                        .add(communicatoinLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(communicationLabelText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                    .add(costPanelLayout.createSequentialGroup()
                        .add(totalLabel)
                        .add(76, 76, 76)
                        .add(totalLabelText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)))
                .addContainerGap())
        );
        costPanelLayout.setVerticalGroup(
            costPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(costPanelLayout.createSequentialGroup()
                .add(costPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(executionLabel)
                    .add(executionLabelText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(costPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(communicatoinLabel)
                    .add(communicationLabelText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(costPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(totalLabelText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(totalLabel))
                .addContainerGap())
        );

        getContentPane().add(costPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 630, 100));

        reportTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
        reportTitleLabel.setText("Simulation Report:");
        getContentPane().add(reportTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 170, 39));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/ubc/magic/profiler/simulator/view/resources/report.jpg"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 261, 45));
        imageLabel.getAccessibleContext().setAccessibleName("reportImage");

        closeButton.setText("Close");
        closeButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        closeButton.setMaximumSize(new java.awt.Dimension(11, 30));
        closeButton.setMinimumSize(new java.awt.Dimension(11, 30));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 127, 32));

        hostTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Host"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPane.setViewportView(hostTable);

        getContentPane().add(tableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 630, 115));

        doneLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        doneLabel.setForeground(new java.awt.Color(1, 148, 55));
        getContentPane().add(doneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 160, 20));
    }// </editor-fold>//GEN-END:initComponents

private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
    this.setVisible(false);
    this.dispose();
}//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel communicationLabelText;
    private javax.swing.JLabel communicatoinLabel;
    private javax.swing.JPanel costPanel;
    private javax.swing.JLabel doneLabel;
    private javax.swing.JPanel exchangePanel;
    private javax.swing.JLabel executionLabel;
    private javax.swing.JLabel executionLabelText;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel fromLabelText;
    private javax.swing.JTable hostTable;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel reportTitleLabel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel toLabel;
    private javax.swing.JLabel toLabelText;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalLabelText;
    // End of variables declaration//GEN-END:variables

    private boolean mHostAdded = false;     
}
